version: "3.8"

networks:
  dev:
    name: dev

services:

  apache:
    image: ${IMG_APACHE}
    working_dir: /app
    networks:
      - dev
    ports:
      - 80:80
    volumes:
      - ./configs/apache:/usr/local/apache2/conf
      - ./docs:/app
