# /app is a working dir in a container binded to a project folder

# where to process files
source: /app/src/jekyll

# where to put generated site
destination: /app/dist

# keep files in destination folder from deleting when rebuilding site
keep_files: ["css", "js", "img"]
